sudo: false
dist: trusty
language: java
jdk:
  - openjdk8

# addons section is a workaround for a Travis issue with missing JUnit jars:
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - ant
      - ant-optional

# set up a small VuFind and load some records
before_script:
  - if [ ! -d vufind/.git ]; then git clone https://github.com/vufind-org/vufind.git; fi;
  - cd vufind
  - git pull
  - phpenv global 7.1
  - composer install
  - export VUFIND_HOME=$(pwd)
  - ./solr.sh start
  - ./import-marc-auth.sh tests/data/authority/authorityauth.mrc marc_auth_ils.properties
  - ./import-marc.sh tests/data/authoritybibs.mrc
  - ./index-alphabetic-browse.sh
  - ./solr.sh stop
  - cd ..

script:
  - ant test -Dvufind.dir=vufind
  - cd $VUFIND_HOME ; rm -rf solr/vufind ; rm import/*.log ; git reset --hard

cache:
  directories:
    - vufind
